name: C CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install --yes build-essential cppcheck libmicrohttpd-dev libcjson-dev libsqlite3-dev libssl-dev
      - name: Build and test
        run: make check
      - name: Build sanitizers
        run: make sanitize
